### PR TITLE
Order only by house/initial number then address string

### PR DESCRIPTION
**Pull request by camilleldn**

### CODE REVIEW

**Comment by lgonczar** [comment]
The changes match the corresponding updater changes well. Not sure about the lack of flat sorting.

**Comment by lgonczar** [comment]
Flat sorting explained.

Looks good.

**Comment by camilleldn** [comment]
To finish this story:
- add a lowercase analyser for the postcode index. sorting by address_string without an analyser set to lowercase would mean that `Zoo` would come before `Aardvark`
- change the acceptance tests for the feeder to reflect the type of ordering we want (order 1 on the story comments)

Finally there is no zoo, aardvark or dinosaur emoji which makes this last pull request very disappointing.

**Comment by lgonczar** [comment]
Instead of the lowercase analyser, we should just store address_string as lowercase. We only use that field for searching, so we can and should do it. We'll save half the space this way.

**Comment by lgonczar** [comment]
Elasticsearch keeps lowercase address data now - https://github.com/LandRegistry/digital-register-elasticsearch-updater/pull/26

**Pull request merged**
