### PR TITLE
Feature/us324 restrict summary access

### PR DESCRIPTION
**Pull request by RichardProsser**
I wish this to be reviewed before it gets too unwieldy!

Thanks ...

Richard

### CODE REVIEW

**Comment by RichardProsser** [comment]
'cart_id' should be derived from title number and 'last published' date, rather than user id. and current timestamp - it should correspond to a 'product' in other words.

This feature is not really used however so this change can be implemented later; it was intended for VAT receipts but a different mechanism was employed.

**Comment by mattgirdler** [comment]
Can't see any issues

**Comment by woodingd** [comment]
lgtm :+1:

**Comment by Pheonnexx** [comment]
LGTM

**Comment by RichardProsser** [comment]
rebase conducted successfully, lr-run-unit-tests ran OK.

**Pull request merged**
