### PR TITLE
Hotfix/fix paginated results count

### PR DESCRIPTION
**Pull request by nickgravgaard**

### CODE REVIEW

**Comment by lgonczar** [comment]
Looks good. We should have the covered case tested, as well.

**Comment by lgonczar** [comment]
Looks alright

**Comment by lgonczar** [comment]
Can go as a hotfix, but I gave it a thought and the code should never proceed through the happy path if there's no title_number in the record. In this case we should log the problem and fail (500), as we should have never allowed for this situation. Therefore, formatting the entries should never change their number.

**Comment by camilleldn** [comment]
If this is a hotfix, should it be going directly to master? (code LGTM though)

**Pull request closed without merging**
