### PR TITLE
Move default log location to /var/log

### PR DESCRIPTION
**Pull request by camilleldn**

### CODE REVIEW

**Comment by AndrewGorton** [comment]
I wonder if we should be using syslog for logging, rather than logging directly. Or possibly the python-logstash bindings if we want to directly forward to ELK. Maybe WebOps have a requirement around this?

**Comment by camilleldn** [comment]
@AndrewGorton: this config change has been discussed with @djsd123 :)

**Comment by camilleldn** [comment]
if different requirements emerge in the future, we can have separate configs for separate environments

**Comment by lgonczar** [comment]
LGTM. Can merge once Andrew's happy.

**Comment by AndrewGorton** [comment]
Happy to be pragmatic and let it be merged. 

All the other places I've worked on delegate to syslog for system-level logging because that means WebOps have full control of the logging mechanisms by Puppetising the syslog config.

**Pull request merged**
